name: Deploy static site to Azure Web App - app-asapHvac

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6FAB809D303A4F85BBF8733A7B45C4F3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_29DEAD8D74B4448395DD4F45A483C174 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BE9BAF8C711C4D21B10A8F4872F71F96 }}

      - name: Deploy static site to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-asapHvac'
          slot-name: 'Production'
          package: .
          